const bookData = [
  {
    author: ["Jessica Davis", "Michael Lewis"],
    language: "en",
    subject: ["Psychology", "Self-help"],
    title: "Mind Over Matter: The Power of Positive Thinking",
  },
  {
    author: ["Carlos Gonzalez", "Sofia Fernandez"],
    language: "es",
    subject: ["Medicina", "Salud"],
    title: "Los Secretos de la Salud",
  },
  {
    author: ["Yuji Nakamura", "Aki Tanaka"],
    language: "ja",
    subject: ["Business", "Economics"],
    title: "The Japanese Economic Miracle",
  },
  {
    author: ["Giovanni Rossi", "Giulia Bianchi"],
    language: "it",
    subject: ["Art", "History"],
    title: "La Scultura Italiana",
  },
  {
    author: ["Mohammed Ahmed", "Fatima Ali"],
    language: "ar",
    subject: ["Religion", "Philosophy"],
    title: "The Quran and Islam",
  },
  {
    author: ["Elena Petrova", "Anna Ivanova"],
    language: "ru",
    subject: ["Literature", "Poetry"],
    title: "The Russian Soul",
  },
  {
    author: ["Min-Soo Kim", "Ji-Hyun Park"],
    language: "ko",
    subject: ["History", "Culture"],
    title: "The Beauty of Korea",
  },
  {
    author: ["Mohammed Ali", "Fatima Khan"],
    language: "ar",
    subject: ["Politics", "International Relations"],
    title: "The Middle East: A Complex Reality",
  },
  {
    author: ["Maria Hernandez", "Juan Sanchez"],
    language: "es",
    subject: ["Education", "Pedagogy"],
    title: "La Educación del Futuro",
  },
  {
    author: ["Emily Chen", "Jennifer Wong"],
    language: "zh",
    subject: ["Science", "Technology"],
    title: "STEM Education: Empowering the Next Generation",
  },
  {
    author: ["Roberto Silva", "Amanda Perez"],
    language: "pt",
    subject: ["History", "Culture"],
    title: "The History of Brazil",
  },
  {
    author: ["Olivia Brown", "Jack Lewis"],
    language: "en",
    subject: ["Psychology", "Self-help"],
    title: "Overcoming Anxiety and Depression",
  },
  {
    author: ["Jorge Martinez", "Ana Ramirez"],
    language: "es",
    subject: ["History", "Politics"],
    title: "La Conquista de América",
  },
  {
    author: ["Hiroshi Nakamura", "Aiko Tanaka"],
    language: "ja",
    subject: ["Science", "Technology"],
    title: "The Future of Robotics",
  },
  {
    author: ["Luisa Perez", "Pedro Sanchez"],
    language: "es",
    subject: ["Psychology", "Self-help"],
    title: "El Poder de la Mente",
  },
  {
    author: ["John Smith", "Emily Brown"],
    language: "en",
    subject: ["History", "Politics"],
    title: "The Rise and Fall of Empires",
  },
  {
    author: ["Juan Martinez", "Maria Garcia"],
    language: "es",
    subject: ["Literature", "Poetry"],
    title: "Poesía de Amor y Desamor",
  },
  {
    author: ["Hiroshi Yamamoto", "Aya Tanaka"],
    language: "ja",
    subject: ["Science", "Technology"],
    title: "Artificial Intelligence and Robotics",
  },
  {
    author: ["Elena Petrova", "Ivan Ivanov"],
    language: "ru",
    subject: ["Philosophy", "Religion"],
    title: "The Meaning of Life",
  },
  {
    author: ["Mohammed Ali", "Aisha Khan"],
    language: "ar",
    subject: ["Politics", "International Relations"],
    title: "The Arab Spring",
  },
  {
    author: ["Carlos Gonzalez", "Sofia Hernandez"],
    language: "es",
    subject: ["Medicina", "Salud"],
    title: "La Medicina Natural",
  },
  {
    author: ["Emily Chen", "Jennifer Wong"],
    language: "zh",
    subject: ["Business", "Economics"],
    title: "The Global Economy",
  },
  {
    author: ["Giovanni Rossi", "Giulia Bianchi"],
    language: "it",
    subject: ["Art", "History"],
    title: "Leonardo da Vinci and the Renaissance",
  },
  {
    author: ["Olivia Brown", "Jack Lewis"],
    language: "en",
    subject: ["Psychology", "Self-help"],
    title: "The Art of Happiness",
  },
  {
    author: ["Min-Soo Kim", "Ji-Hyun Park"],
    language: "ko",
    subject: ["Culture", "Society"],
    title: "The Korean Wave",
  },
  {
    author: ["Mohammed Ahmed", "Fatima Ali"],
    language: "ar",
    subject: ["Religion", "Philosophy"],
    title: "The Quran and Its Interpretation",
  },
  {
    author: ["Roberto Silva", "Amanda Perez"],
    language: "pt",
    subject: ["History", "Politics"],
    title: "The Portuguese Colonial Empire",
  },
  {
    author: ["Maria Hernandez", "Juan Sanchez"],
    language: "es",
    subject: ["Education", "Pedagogy"],
    title: "La Educación en el Siglo XXI",
  },
  {
    author: ["Luisa Perez", "Pedro Rodriguez"],
    language: "es",
    subject: ["Psychology", "Self-help"],
    title: "La Superación Personal",
  },
  {
    author: ["Jorge Martinez", "Ana Ramirez"],
    language: "es",
    subject: ["History", "Culture"],
    title: "El Patrimonio Cultural de México",
  },
  {
    author: ["Lucas Anderson", "Sophie Thompson"],
    language: "en",
    subject: ["History", "Politics"],
    title: "The Rise and Fall of the British Empire",
  },
  {
    author: ["Pablo Rodriguez", "Maria Hernandez"],
    language: "es",
    subject: ["Medicina", "Salud"],
    title: "La Alimentación y la Salud",
  },
  {
    author: ["Yusuke Nakamura", "Miyuki Tanaka"],
    language: "ja",
    subject: ["Art", "Design"],
    title: "The Art of Illustration",
  },
  {
    author: ["Carla Costa", "João Silva"],
    language: "pt",
    subject: ["History", "Culture"],
    title: "The Legacy of the Portuguese Discoveries",
  },
  {
    author: ["Ahmed Mohammed", "Fatima Ali"],
    language: "ar",
    subject: ["Religion", "Philosophy"],
    title: "Islam and Modernity",
  },
  {
    author: ["Anna Petrova", "Irina Ivanova"],
    language: "ru",
    subject: ["Science", "Technology"],
    title: "The Future of Space Exploration",
  },
  {
    author: ["Min-Jae Kim", "Hae-Won Park"],
    language: "ko",
    subject: ["Business", "Economics"],
    title: "The Korean Economic Miracle",
  },
  {
    author: ["Mohammed Ali", "Aisha Khan"],
    language: "ar",
    subject: ["Politics", "International Relations"],
    title: "The Geopolitics of the Middle East",
  },
  {
    author: ["Pedro Fernandez", "Sofia Sanchez"],
    language: "es",
    subject: ["Education", "Pedagogy"],
    title: "La Pedagogía del Siglo XXI",
  },
  {
    author: ["Xiao Chen", "Wei Zhang"],
    language: "zh",
    subject: ["Science", "Engineering"],
    title: "The Science of Materials",
  },
  {
    author: ["Roberto Silva", "Amanda Perez"],
    language: "pt",
    subject: ["History", "Culture"],
    title: "The History of Brazil",
  },
  {
    author: ["Emma Smith", "David Brown"],
    language: "en",
    subject: ["Psychology", "Self-help"],
    title: "The Psychology of Motivation",
  },
  {
    author: ["Jorge Martinez", "Ana Ramirez"],
    language: "es",
    subject: ["History", "Politics"],
    title: "La Conquista de América",
  },
  {
    author: ["Takeshi Nakamura", "Aya Tanaka"],
    language: "ja",
    subject: ["Science", "Technology"],
    title: "The Future of Nanotechnology",
  },
  {
    author: ["Luisa Perez", "Pedro Sanchez"],
    language: "es",
    subject: ["Psychology", "Self-help"],
    title: "El Poder de la Mente",
  },
];
